name: Deploy docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: setup-php
      uses: khs1994-docker/actions-setup-php@0.0.1

    - name: Composer and npm
      run: composer install && npm install

    - name: Generate static files
      run: npm run production

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: build_production # The folder the action should deploy.
